name: module3_task3

on:
  push:
    branches: [master]

    tags:
        - "1.0.0"
  schedule:
    - cron: "30 00 * * *"

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      # so the job can access it
      - name: "Checkout"
        uses: actions/checkout@v3

      # Ensure all the required tools are installed prior to any make target
      - name: "setup"
        run: cd module3_task3 && ./setup.sh

      # Check syntax on markdown files
      - name: "make build"
        run: cd module3_task3 && make build

      # Check syntax on markdown files
      - name: Run markdownlint on markdown files
        run: make lint -C module3_task3/

      # Produce a zip file containing the dist folder
      - name: "Archive the dist folder inside a zip file"
        run: make package -C module3_task3/

      # Additional steps form past module
      - name: "Run additional make rules"
        run: |
          make unit-tests -C module3_task3/
          make integration-tests -C module3_task3/
          make validate -C module3_task3/
      # Archive the zip file as artifact
      - name: "Archive code coverage results"
        uses: actions/upload-artifact@v3
        with:
          name: Archive awesome-website.zip as artifact
          path: module3_task3/awesome-website.zip

      #Generate a release with the archive and the content of DEPLOY.md
      - name: "create a GitHub Release"
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/1.0.0')
        with:
            files: module3_task3/awesome-website.zip
            body_path: module3_task3/DEPLOY.md
